#!/bin/bash
#
# auroraborealisd - Aurora Borealis Core daemon
#
# chkconfig: 345 80 20
# description: Aurora Borealis Coin P2P network daemon
# processname: auroraborealisd
#

. /etc/init.d/functions

if [ -f /etc/sysconfig/auroraborealisd ]; then
    . /etc/sysconfig/auroraborealisd
fi

RETVAL=0

prog=auroraborealisd

lockfile=${AURORABOREALISD_LOCKFILE-/var/lock/subsys/auroraborealisd}
daemon_bin=${AURORABOREALISD_BIN-/usr/bin/auroraborealisd}
daemon_opts=${AURORABOREALISD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS "$daemon_bin" $daemon_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch "$lockfile"
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc "$prog"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f "$lockfile"
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status "$prog"
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $RETVAL
