description "Aurora Borealis Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env AURORABOREALISD_BIN="/usr/bin/auroraborealisd"
env AURORABOREALISD_USER="auroraborealis"
env AURORABOREALISD_GROUP="auroraborealis"

env AURORABOREALISD_PIDDIR="/run/auroraborealis"
env AURORABOREALISD_PIDFILE="/run/auroraborealis/auroraborealisd.pid"

env AURORABOREALISD_CONFIGFILE="/etc/auroraborealis/auroraborealis.conf"
env AURORABOREALISD_DATADIR="/var/lib/auroraborealis"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    if [ ! -f "$AURORABOREALISD_CONFIGFILE" ]; then
        echo "ERROR: Missing configuration file:"
        echo "$AURORABOREALISD_CONFIGFILE"
        exit 1
    fi

    mkdir -p "$AURORABOREALISD_PIDDIR"
    chmod 0755 "$AURORABOREALISD_PIDDIR"
    chown "$AURORABOREALISD_USER:$AURORABOREALISD_GROUP" \
          "$AURORABOREALISD_PIDDIR"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$AURORABOREALISD_PIDFILE" \
    --chuid "$AURORABOREALISD_USER:$AURORABOREALISD_GROUP" \
    --exec "$AURORABOREALISD_BIN" \
    -- \
    -pid="$AURORABOREALISD_PIDFILE" \
    -conf="$AURORABOREALISD_CONFIGFILE" \
    -datadir="$AURORABOREALISD_DATADIR" \
    -disablewallet \
    -daemon
